headless: True
offline: True
resolution:
  - 1080 
  - 1920
num_objects: 
  max: 2
  min: 2
num_samples:
  max: 1
  min: 1
icl:  
  max: 0
  min: 0
num_iterations: 150
vlm_cls: GeminiAgent
vlm_kwargs:
  model: 'gemini-1.5-flash'
  # name: 8b
  # quantize: False
  # device_map: Auto
  # do_sample: True
  # use_flash_attention_2: True

data_path: 'explore'
log_freq: 5
shuffle: True
dynamic: True
inner_loop: 1
