headless: True
offline: True
resolution:
  - 1080 
  - 1920
num_objects: 
  max: 3
  min: 2
num_samples:
  max: 3
  min: 1
icl:  
  max: 0
  min: 0
num_iterations: 500
vlm_cls: LLaVaAgent
vlm_kwargs:
  llm: mistral
  size: 7b
  quantize: False
data_path: '10scenes2000'
log_freq: 50
shuffle: True